# This workflow will build the docker image and push to Azure Container Registry
# This workflow will do a clean install of python dependencies, run tests, build the docker images and deploy to Azure Container Instances

name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          registry: rabtcr.azurecr.io
          name: rabtcr.io/RABT-image-browser
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
